title: Zenseact Open Dataset

# Build settings
theme: minimal-mistakes-jekyll
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"

include:
  - _data
  - _pages

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      author_profile: true

footer:
  links:
    - label: "Zenseact"
      icon: "fas fa-fw fa-building"
      url: "https://zenseact.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zenseact"

atom_feed:
  hide: true
